name: Deploy to Dev
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      S3_URL: ${{ secrets.S3_URL }}
      REACT_APP_API_DOMAIN: ${{ secrets.API_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn
      - run: yarn run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
      - run: yarn s3p sync -y -t $S3_URL
